### ISSUE TITLE
Please wrap REPOX's webserver

### ISSUE THREAD

**Issue by calcnerd256** [OULibraries/ansible-role-repox#8]
It doesn't want to face the world.

**Comment by jsnshrmn** [comment]
Chris, I'd like you to take a swing at this. Basically, the goal is to wrap repox (or some parts of it) with basic auth. Things like OAI-PMH should be harvestable without a login, but any kind of administrative task should have an additional layer of authentication.  You might be able to tackle this natively with tomcat configuration, or you might need to set up a local apache2 reverse proxy.  Nginx would actually be a bad fit for this, because it requires a re-authentication for every request inside a basic auth directory.

**Comment by jsnshrmn** [comment]
closed by #13
